"use client"

import { useState } from "react"
import type { Locale } from "@/types"
import ActionableToolCards from "./ActionableToolCards"
import AiCounselor from "./AiCounselor"
import BreathingGuide from "./BreathingGuide"
import HealingToolbox from "./HealingToolbox"
import HeroSection from "./HeroSection"
import MeditationController from "./MeditationController"
import ResonanceWall from "./ResonanceWall"
import { Sparkles } from "lucide-react"

const MEDITATION_LABELS: Record<string, { title: string; desc: string; btn: string }> = {
  zh: { title: "🧘 AI 引导冥想", desc: "基于你的情绪状态，由 AI 动态生成专属冥想引导。呼吸、画面、声音三位一体，深度沉浸。", btn: "开始冥想" },
  en: { title: "🧘 AI-Guided Meditation", desc: "Dynamic meditation script generated by AI based on your emotional state. Breath, visuals, and sound — deeply immersive.", btn: "Start Meditation" },
}

export default function InteractiveAreas({
  lang,
  heroTitle,
  heroSubtitle,
  heroCtaText,
}: {
  lang: Locale
  heroTitle: string
  heroSubtitle: string
  heroCtaText: string
}) {
  const [showBreathing, setShowBreathing] = useState(false)
  const [showMeditation, setShowMeditation] = useState(false)
  const labels = MEDITATION_LABELS[lang] || MEDITATION_LABELS.en

  return (
    <>
      <HeroSection title={heroTitle} subtitle={heroSubtitle} ctaText={heroCtaText} />

      {/* Actionable Tool Cards — triggers BreathingGuide via internal callback */}
      <section className="px-4 sm:px-6 pb-6">
        <div className="max-w-5xl mx-auto">
          <ActionableToolCards
            locale={lang}
            onStartBreathing={() => setShowBreathing(true)}
          />
        </div>
      </section>

      {/* AI-Guided Meditation Entry */}
      <section className="px-4 sm:px-6 pb-10">
        <div className="max-w-5xl mx-auto">
          <div className="relative overflow-hidden rounded-2xl border border-dc-accent/20 bg-gradient-to-br from-dc-accent/5 via-transparent to-dc-surface/10 p-6 sm:p-8">
            {/* Decorative glow */}
            <div className="absolute -top-20 -right-20 w-40 h-40 rounded-full bg-dc-accent/5 blur-3xl pointer-events-none" />
            <div className="absolute -bottom-10 -left-10 w-32 h-32 rounded-full bg-dc-accent/5 blur-2xl pointer-events-none" />

            <div className="relative z-10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div className="flex-1">
                <h3 className="text-lg font-semibold text-dc-text mb-2">{labels.title}</h3>
                <p className="text-sm text-dc-muted leading-relaxed max-w-md">{labels.desc}</p>
              </div>
              <button
                onClick={() => setShowMeditation(true)}
                className="flex-shrink-0 flex items-center gap-2 px-6 py-3 rounded-xl bg-dc-accent/15 hover:bg-dc-accent/25 border border-dc-accent/30 text-dc-accent font-medium text-sm transition-all duration-200 hover:shadow-sm hover:shadow-dc-accent/10"
              >
                <Sparkles className="w-4 h-4" />
                {labels.btn}
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* AI Counselor */}
      <section id="ai-counselor" className="min-h-[70vh] flex items-center justify-center px-4 sm:px-6 pt-10">
        <div className="w-full">
          <AiCounselor />
        </div>
      </section>

      <HealingToolbox />

      {/* Resonance Wall */}
      <section id="resonance-wall" className="w-full py-16 sm:py-24 px-4 sm:px-6">
        <div className="max-w-2xl mx-auto">
          <ResonanceWall />
        </div>
      </section>

      {/* Breathing Guide Modal — triggered by ActionableToolCards */}
      {showBreathing && (
        <BreathingGuide onClose={() => setShowBreathing(false)} />
      )}

      {/* AI-Guided Meditation Modal */}
      {showMeditation && (
        <MeditationController onClose={() => setShowMeditation(false)} />
      )}
    </>
  )
}
